First API test case for travel endpoint
travelsheets/travelsheets-api pull request #9
Opened 2018-04-02 16:19 UTC by qmachard

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| Related tickets |
| License         | MIT

2018-04-02 22:14 UTC, loic425 requested changes

2018-04-02 22:14 UTC, loic425 commented on app/config/config_test.yml
> +    pass_phrase:        'test'
une petite ligne vide de fin de fichier :)

2018-04-02 22:14 UTC, loic425 commented on src/CoreBundle/Resources/config/services.yml
> +    public: true
pareil

2018-04-02 22:14 UTC, loic425 commented on tests/Controller/TravelApiTest.php
> +
ligne vide en trop

2018-04-02 22:14 UTC, loic425 commented on tests/Controller/TravelApiTest.php
> + * Created by PhpStorm.
Je te conseille de créer ton template pour ton projet avec la licence qui va bien.

2018-04-02 22:14 UTC, loic425 commented on tests/Controller/TravelApiTest.php
> +     * Test forbidden access to user without token
en fait il faut au maximum que le nom de la méthode de ton test décrive ce que tu testes. Il n'y a donc jamais besoin de commentaire.

2018-04-02 22:14 UTC, loic425 commented on tests/Responses/Expected/error/unauthorized_response.json
> +}
la petite ligne vide

2018-04-02 22:14 UTC, loic425 commented on tests/Responses/Expected/travel/list_future_response.json
> +}
pareil

2018-04-02 22:14 UTC, loic425 commented on tests/Responses/Expected/travel/list_past_response.json
> +      "dateStart": @string@,
tu peux vérifier que ce soit un string de type date

2018-04-03 21:09 UTC, qmachard commented on tests/Controller/TravelApiTest.php
> + * Created by PhpStorm.
Tu pourras me montrer ? Merci 😄

2018-04-03 21:11 UTC, qmachard commented on tests/Responses/Expected/travel/list_past_response.json
> +      "dateStart": @string@,
Pareil, tu me montreras ça :)

2018-04-07 09:47 UTC, closed without merging